imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

parameters:
    app_name: "Webedit"
    form_theme: "::form.html.twig"

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        app_name: %app_name%
        system_email: %system_email%
    form:
        resources:
            - '::fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# FOS USer Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Siriux\UserBundle\Entity\User
    use_listener: false
    service:
      user_manager: siriux_user.user_manager
    template:
      theme: %form_theme%
    from_email:
        address: %system_email%
        sender_name: %app_name%
    registration:
        form:
            type: siriux_user_registration
        confirmation:
            enabled: true
    profile:
        form:
            type: siriux_user_profile

