services:
    siriux_user.user_manager:
        class: Siriux\UserBundle\Entity\UserManager
        arguments:
          - "@security.encoder_factory"
          - "@fos_user.util.username_canonicalizer"
          - "@fos_user.util.email_canonicalizer"
          - "@fos_user.entity_manager"
          - %fos_user.model.user.class%

    siriux_user.registration.form.type:
        class: Siriux\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: siriux_user_registration }

    siriux_user.profile.form.type:
        class: Siriux\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: siriux_user_profile }
